# Generated by Django 5.1.1 on 2024-09-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_court'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Court',
        ),
    ]
